export const approvalLabAbi = [
  {
    type: 'function',
    name: 'progressOf',
    inputs: [{ name: 'student', type: 'address' }],
    outputs: [{
      name: 'p',
      type: 'tuple',
      components: [
        { name: 'drained', type: 'bool' },
        { name: 'revoked', type: 'bool' },
        { name: 'round2Started', type: 'bool' },
        { name: 'round2Tested', type: 'bool' },
        { name: 'round2Passed', type: 'bool' },
        { name: 'fundsRecovered', type: 'bool' },
        { name: 'complete', type: 'bool' },
        { name: 'secondsExposed', type: 'uint64' },
        { name: 'round1Allowance', type: 'uint256' },
        { name: 'round2Allowance', type: 'uint256' },
        { name: 'audRound1Allowance', type: 'uint256' },
        { name: 'audRound2Allowance', type: 'uint256' },
      ],
    }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'badgeOf',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  { type: 'function', name: 'completeRecovery', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'enterRound2', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'claimCompletionReward', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  {
    type: 'function',
    name: 'hasCompleted',
    inputs: [{ name: 'student', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
] as const
